services:
  app:
    image: ${APP_IMAGE}

    container_name: hack-spring
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul

      # Spring이 MySQL 컨테이너로 붙도록
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    restart: unless-stopped
