spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:cowork}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:${MYSQL_USER:cowork}}
    password: ${MYSQL_PASSWORD:cowork1234}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        show_sql: false
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  sso-temp-token-expiry: 300